name: env

channels:
  - defaults
  - anaconda

dependencies:
  - python>=3.10.4
  - ipykernel>=6.9.1
  - statsmodels>=0.13.2
  - numpy>=1.22.4
  - matplotlib>=3.5.2
  - tqdm>=4.64.0  
  - scikit-learn>=1.1.1
  - pandas>=1.4.3
  - cartopy>=0.18.0
  - pip>=22.1.2
  - pip:
          - regionmask>=0.9.0
          - py-bobyqa>=1.3
          - cmcrameri>=1.4
